name: Run Tests and Publish Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Start Selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1

      - name: checkout
        uses: actions/checkout@v2

      - name: Build with gradle
        run: ./gradlew clean build
