name: Run Tests and Publish Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: store docker image cache
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Start Selenoid server
      uses: n-ton4/selenoid-github-action@master
      id: start-selenoid
      continue-on-error: false
      with:
        version: 1.10.1
        args: -limit 10
        browsers: chrome
        last-versions: 1

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with gradle
      run: ./gradlew clean :test --tests "co.com.test.certification.runners.MainRunner"

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/site

    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/site
